
title: Emre Kaya # your name (or website title) here
logo:  "/images/IMG_5776.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://nodds.khas.edu.tr">Nodds</a> 
  <br><br>
  <a href="https://nodds.khas.edu.tr">Blog</a> 
  <br><br>
  <a href="https://nodds.khas.edu.tr">Blog</a> 
  
theme: jekyll-theme-minimal
github:
  is_project_page: false
