title: Emre Kaya # your name (or website title) here
logo: "/images/IMG_0095.jpg"  # your photo (or logo) here
<img src="images/IMG_0095.jpg?raw=true" height="12"/>
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://nodds.khas.edu.tr">Nodds</a> 
  <br><br>
  <a href="https://nodds.khas.edu.tr">Blog</a> 
  
theme: jekyll-theme-minimal
